#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  $PWD"/.husky/bash-message.sh" "Cannot push to main. Please push changes to a new branch."
  exit 1
fi